### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by Sierpinski35** [DianaSuvorova/atom-karma-test-runner#8]
[Enter steps to reproduce:]

1. Install electron-vue as described on [project](https://github.com/SimulatedGREG/electron-vue) page
2. Import project in atom. Select _test/unit/specs/LandingPage.spec.js _
3. Run atom-karma-test-runner to spawn error above.

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [atom-karma-test-runner](https://github.com/DianaSuvorova/atom-karma-test-runner) package 1.1.1

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /home/sob/.atom/packages/atom-karma-test-runner/lib/getContext.js:11

TypeError: editor.getPath is not a function
    at getContext (/packages/atom-karma-test-runner/lib/getContext.js:11:29)
    at Object.run (/packages/atom-karma-test-runner/lib/atom-karma-test-runner.js:60:28)
    at HTMLElement.atomKarmaTestRunnerRun (/packages/atom-karma-test-runner/lib/atom-karma-test-runner.js:31:48)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:48 atom-karma-test-runner:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:38.7.0 application:add-project-folder (atom-pane.pane)
     -0:19.4.0 atom-karma-test-runner:run (div.tool-panel.tree-view)
```

### Non-Core Packages

```
api-workbench 0.8.47 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atom-karma-test-runner 1.1.1 
auto-detect-indentation 1.3.0 
build 0.69.0 
build-gradle 0.6.0 
busy 0.7.0 
busy-signal 1.4.3 
intentions 1.1.5 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-ui-default 1.6.10 
raml 0.2.0 
vue-autocompile 0.0.6 
vue-element-ui-snippets 0.7.0 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.12.1 
```

**Comment by Sierpinski35** [comment]
Could be related to this [issue](https://github.com/ganarajpr/image2react/issues/1)?
